### ISSUE TITLE
Too dark preview colors in create new question preview

### ISSUE THREAD

**Issue by Xupi** [agasior093/InterviewPrepApp#12]
![image](https://user-images.githubusercontent.com/26859826/77253202-19440a00-6c59-11ea-8ce4-81518cea555f.png)

**Comment by Xupi** [comment]
![image](https://user-images.githubusercontent.com/26859826/79046410-12ce0000-7c11-11ea-9668-2852424692cc.png)

is this better for You?

**Comment by agasior093** [comment]
Check out how the made in on Stackoverflow, in my opinion adding white editor on dark theme isnt looking too great

![image](https://user-images.githubusercontent.com/24475158/79064086-26777600-7ca6-11ea-829e-0b3499f0f8b5.png)
